#!/bin/bash
make V=1 && \
    \ls -l /mnt/d/fab-agon-emulator/sdcard/mos/aed.bin && \
    cp bin/aed.bin /mnt/d/fab-agon-emulator/sdcard/mos && \
    \ls -l /mnt/d/fab-agon-emulator/sdcard/mos/aed.bin
